/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
/**********************************************************************************************************************
 * FILE: Cpu0_Main.c for nre one after debuging
 *********************************************************************************************************************/

#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include "Ifx_Cfg_Ssw.h"
#include "IfxPort.h"
#include "IfxStm.h"

/* Pin numbers on PORT00 */
#define LED1_PIN    5       /* P00.5 */
#define LED2_PIN    6       /* P00.6 */
#define BUTTON_PIN  7       /* P00.7 */

IFX_ALIGN(4) IfxCpu_syncEvent cpuSyncEvent = 0;


void core0_main(void)
{
    /* Enable CPU interrupts */
    IfxCpu_enableInterrupts();

    /* Disable watchdogs for this learning project */
    IfxScuWdt_disableCpuWatchdog(
            IfxScuWdt_getCpuWatchdogPassword());

    IfxScuWdt_disableSafetyWatchdog(
            IfxScuWdt_getSafetyWatchdogPassword());

    /* Synchronize CPU cores */
    IfxCpu_emitEvent(&cpuSyncEvent);
    IfxCpu_waitEvent(&cpuSyncEvent, 1);


    /**************** GPIO CONFIGURATION ****************/

    /* LED1: P00.5 -> GPIO push-pull output */
    IfxPort_setPinModeOutput(
            &MODULE_P00,
            LED1_PIN,
            IfxPort_OutputMode_pushPull,
            IfxPort_OutputIdx_general);

    /* LED2: P00.6 -> GPIO push-pull output */
    IfxPort_setPinModeOutput(
            &MODULE_P00,
            LED2_PIN,
            IfxPort_OutputMode_pushPull,
            IfxPort_OutputIdx_general);

    /* BUTTON1: P00.7 -> GPIO input */
    IfxPort_setPinModeInput(
            &MODULE_P00,
            BUTTON_PIN,
            IfxPort_InputMode_noPullDevice);


    /**************** INITIAL LED STATE ****************/

    /*
     * LEDs are active-low:
     *
     * HIGH -> LED OFF
     * LOW  -> LED ON
     */

    IfxPort_setPinHigh(&MODULE_P00, LED1_PIN);
    IfxPort_setPinHigh(&MODULE_P00, LED2_PIN);


    /**************** VARIABLES ****************/

    /*
     * TRUE  -> button released
     * FALSE -> button pressed
     */
    boolean previousButtonState = TRUE;

    /*
     * state:
     *
     * 0 = both LEDs OFF
     * 1 = LED1 ON, LED2 OFF
     * 2 = LED1 OFF, LED2 ON
     * 3 = both LEDs ON
     */
    uint8 state = 0;


    /**************** MAIN LOOP ****************/

    while (1)
    {
        /* Read BUTTON1 on P00.7 */
        boolean currentButtonState =
                IfxPort_getPinState(&MODULE_P00, BUTTON_PIN);


        /*
         * Detect falling edge:
         *
         * previous = TRUE  (released)
         * current  = FALSE (pressed)
         */
        if ((previousButtonState == TRUE) &&
            (currentButtonState == FALSE))
        {
            /* Wait 20 ms for mechanical button debounce */
            IfxStm_waitTicks(
                    &MODULE_STM0,
                    IfxStm_getTicksFromMilliseconds(
                            &MODULE_STM0,
                            20));


            /* Read button again after debounce */
            currentButtonState =
                    IfxPort_getPinState(&MODULE_P00, BUTTON_PIN);


            /* Confirm that button is still pressed */
            if (currentButtonState == FALSE)
            {
                /* Move to next state */
                state++;

                /* After state 3, return to state 0 */
                if (state > 3)
                {
                    state = 0;
                }


                /************** LED STATE MACHINE **************/

                switch (state)
                {
                    case 0:
                        /* Both LEDs OFF */
                        IfxPort_setPinHigh(&MODULE_P00, LED1_PIN);
                        IfxPort_setPinHigh(&MODULE_P00, LED2_PIN);
                        break;


                    case 1:
                        /* LED1 ON, LED2 OFF */
                        IfxPort_setPinLow(&MODULE_P00, LED1_PIN);
                        IfxPort_setPinHigh(&MODULE_P00, LED2_PIN);
                        break;


                    case 2:
                        /* LED1 OFF, LED2 ON */
                        IfxPort_setPinHigh(&MODULE_P00, LED1_PIN);
                        IfxPort_setPinLow(&MODULE_P00, LED2_PIN);
                        break;


                    case 3:
                        /* Both LEDs ON */
                        IfxPort_setPinLow(&MODULE_P00, LED1_PIN);
                        IfxPort_setPinLow(&MODULE_P00, LED2_PIN);
                        break;


                    default:
                        break;
                }
            }
        }


        /*
         * Save current state for next loop iteration.
         *
         * This allows us to detect the next
         * TRUE -> FALSE transition.
         */
        previousButtonState = currentButtonState;
    }
}
